export const TableEndingClockSelect = {
  tableHead: ['Room Alpha'],
  tableTitle: [
    '9:00',
    '9:30',
    '10:00',
    '10:30',
    '11:00',
    '11:30',
    '12:00',
    '12:30',
    '13:00',
    '13:30',
    '14:00',
    '14:30',
    '15:00',
    '15:30',
    '16:00',
    '16:30',
  ],
  tableData: [
    '1',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'The Wise Pesasdsaasdsson123',
    'The Wise Person',
    'The Wise Person',
    '',
  ],
};
export const StartingClockAndEndingClock = {
  tableHead: ['Room Alpha', 'Room Beta', 'Room Chalie'],
  tableTitle: [
    '9:00',
    '9:30',
    '10:00',
    '10:30',
    '11:00',
    '11:30',
    '12:00',
    '12:30',
    '13:00',
    '13:30',
    '14:00',
    '14:30',
    '15:00',
    '15:30',
    '16:00',
    '16:30',
  ],
  tableData: [
    [
      '1',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'The Wise Pesasdsaasdsson123',
      'The Wise Person',
      'The Wise Person',
      '',
    ],
    [
      '2',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'The Wise Pesasdsaasdsson',
      'The Wise Person',
      'The Wise Person',
      '',
    ],
    [
      '3',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'The Wise Pesasdsaasdsson',
      'The Wise Person',
      'The Wise Person',
      '',
    ],
  ],
};
export const UnavailableDatesInMonth = {
  '2019-09-11': {
    selected: true,
    marked: true,
    selectedColor: 'blue',
  },
  '2019-09-16': {marked: true},
  '2019-09-17': {
    marked: true,
    dotColor: 'red',
    activeOpacity: 0,
  },
  '2019-09-04': {disabled: true, disableTouchEvent: true},
};

export const People = [
  'Vladimir',
  'Vladimir1',
  'Vladimir2',
  'Vladimir3',
  'Vladimir4',
  'Vladimir5',
  'Vladimir6',
  'Vladimir7',
  'Vladimir8',
  'Boris',
  'Boris1',
  'Boris2',
  'Boris3',
  'Boris4',
  'Boris5',
  'Boris6',
  'Boris7',
  'Boris8',
];
export const User = [['admin', '123'], ['Nobster', '123']];
